// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ops} from '../models';
import {main} from '../models';

export function ApplyOps(arg1:Array<string>,arg2:Array<ops.Op>):Promise<Array<ops.Verdict>>;

export function DeletePreset(arg1:string):Promise<void>;

export function DiscardUndo():Promise<void>;

export function DryRun(arg1:Array<string>,arg2:Array<ops.Op>):Promise<Array<ops.Verdict>>;

export function GetUndoable():Promise<string>;

export function ListPresets():Promise<Array<string>>;

export function LoadPreset(arg1:string):Promise<Array<ops.Op>>;

export function PickVault():Promise<string>;

export function PreviewNote(arg1:string,arg2:Array<ops.Op>):Promise<Record<string, string>>;

export function SavePreset(arg1:string,arg2:Array<ops.Op>):Promise<void>;

export function Scan(arg1:string):Promise<Array<main.NoteInfo>>;

export function UndoLastRun():Promise<Array<ops.Verdict>>;
