// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyOps(arg1, arg2) {
  return window['go']['main']['App']['ApplyOps'](arg1, arg2);
}

export function DryRun(arg1, arg2) {
  return window['go']['main']['App']['DryRun'](arg1, arg2);
}

export function PickVault() {
  return window['go']['main']['App']['PickVault']();
}

export function PreviewNote(arg1, arg2) {
  return window['go']['main']['App']['PreviewNote'](arg1, arg2);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}
