// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyOps(arg1, arg2) {
  return window['go']['main']['App']['ApplyOps'](arg1, arg2);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function DryRun(arg1, arg2) {
  return window['go']['main']['App']['DryRun'](arg1, arg2);
}

export function GetUndoable() {
  return window['go']['main']['App']['GetUndoable']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function LoadPreset(arg1) {
  return window['go']['main']['App']['LoadPreset'](arg1);
}

export function PickVault() {
  return window['go']['main']['App']['PickVault']();
}

export function PreviewNote(arg1, arg2) {
  return window['go']['main']['App']['PreviewNote'](arg1, arg2);
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function UndoLastRun() {
  return window['go']['main']['App']['UndoLastRun']();
}
